version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: ch
    restart: unless-stopped
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./homeworks/scripts:/tmp/scripts
      - ./data/:/tmp/data/