apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: ClickHouse
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true

- name: ClickHouse
  type: grafana-clickhouse-datasource
  access: proxy
  url: clickhouse-server
  orgId: 1
  jsonData:
    host: clickhouse-server
    database: "test"
    username: "default"
    port: 9000
    protocol: native
  secureJsonData:
    # password: ""