version: '3'
services:
  postgres:
    image: postgres:15.8-bullseye 
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airflow
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - 8001:8080
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - logs:/usr/local/airflow/logs

  clickhouse1:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: clickhouse1
    hostname: clickhouse1    
    ports:
      - "8002:9000"
      - "9123:8123"

volumes:
  pgdata:
  logs:
