version: '3.8'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:15.8
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/:/tmp/data/   

  clickhouse:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - 8123:8123
      - 9000:9000      
    volumes:
      - ./sql/:/tmp/data/      