version: '3.5'

services:
  zookeeper:
    image: 'zookeeper:3.7'
    container_name: zookeeper
    hostname: zookeeper    
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.10
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"
    
  clickhouse1:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: clickhouse1
    hostname: clickhouse1    
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./config.d_01:/etc/clickhouse-server/config.d
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.11
    depends_on:
      - zookeeper
      
  clickhouse2:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: clickhouse2
    hostname: clickhouse2    
    ports:
      - "8003:9000"
      - "9124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./config.d_02:/etc/clickhouse-server/config.d
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.12
    depends_on:
      - zookeeper
      
  clickhouse3:
    image: clickhouse/clickhouse-server:24.8.4.13
    container_name: clickhouse3
    hostname: clickhouse3     
    ports:
      - "8004:9000"
      - "9125:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./config.d_03:/etc/clickhouse-server/config.d
    networks:
      clickhouse-network:
        ipv4_address: 172.24.0.13
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.24.0.0/24